FROM python:3.7

WORKDIR /app


COPY requirements.txt .
RUN pip install -r requirements.txt mysqlclient

COPY . /app

EXPOSE 8585

CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8585" , "--reload"]
